[package]
name = "sudokusolver"
version = "0.1.0"
authors = ["BlockCat <zinoonomiwo@gmail.com>"]

[dependencies]
stacker = "0.1.5"
z3 = { version = "0.3.2", optional = true }

[features]
default = []
z3s = ["z3"]